### ISSUE TITLE
Erreur générée par le script alter-1.0-1.1.sql

### ISSUE THREAD

**Issue by lgasnier** [Irstea/alisma#12]
En repartant d'une installation complète, le script *alter-1.0-1.1.sql* lancé après *create_alisma_v1.0.sql* conduit à l'erreur 
`ERROR 1022 (23000): Can't write; duplicate key in table '#sql-55ce_6'`
qui concerne *a priori* l'avant-avant-dernière instruction du script i.e.
`ALTER TABLE Op_controle ADD CONSTRAINT typo_op_controle_fk
FOREIGN KEY (typo_id)
REFERENCES typo (typo_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;`

**Comment by equinton** [comment]
La même instruction (add constraint typo_op_controle_fk) est présente deux fois dans le script, ce qui explique le message.

Il suffit de ne pas tenir compte du message, et d'exécuter les commandes qui suivent. Je corrige le script pour la prochaine version.
