### ISSUE TITLE
Impossible de valider une opération

### ISSUE THREAD

**Issue by fhissel** [Irstea/alisma#13]
Config : Linux Mint 18.1, Mysql 5.7, Alisma 1.1
Impossible de valider une opération : les onglets "Données mésologiques" et "Données floristiques" sont bien validés (tic vert), mais le premier onglet "Données générales" n'est jamais validé alors que tous les champs sont complétés avec des valeurs plausibles.
Je joins un export XML de l'opération après avoir trafiqué dans la base pour passer le statut en validé et testé les exports SEEE.

`<?xml version="1.0" encoding="UTF-8" ?>
<operations>
<versions>
<softwareVersion>1.1</softwareVersion>
</versions>
<operation>
<nbtaxon_pte>0</nbtaxon_pte>
<robustesse_eqr_value>1.07</robustesse_eqr_value>
<seee_robustesse_value></seee_robustesse_value>
<nbtaxon_bry>5</nbtaxon_bry>
<nbtaxon_lic>0</nbtaxon_lic>
<cs_max>13</cs_max>
<coord_y>2600727</coord_y>
<coef_moy>1.36</coef_moy>
<coord_x>574361</coord_x>
<operateur>Legeay</operateur>
<protocole_libelle>IBMR standard</protocole_libelle>
<ibmr_value>9.28</ibmr_value>
<seee_date></seee_date>
<coef_min>1</coef_min>
<turbidite_libelle>Nulle ou faible</turbidite_libelle>
<ek_nb_robustesse>2</ek_nb_robustesse>
<seee_ibmr></seee_ibmr>
<cd_station>01094000</cd_station>
<seee_nbtaxon_contrib></seee_nbtaxon_contrib>
<longueur>100</longueur>
<robustesse_classe_etat_libelle>Très bon</robustesse_classe_etat_libelle>
<ibmr_ref>9.38</ibmr_ref>
<largeur>15</largeur>
<typo_id>90</typo_id>
<nbtaxon_alg>2</nbtaxon_alg>
<altitude>15</altitude>
<classe_etat_libelle>Très bon</classe_etat_libelle>
<groupe>5</groupe>
<id_statut>1</id_statut>
<seee_version></seee_version>
<nbtaxon_total>11</nbtaxon_total>
<nbtaxon_steno3>0</nbtaxon_steno3>
<nbtaxon_steno2>4</nbtaxon_steno2>
<nbtaxon_steno1>7</nbtaxon_steno1>
<seee_taxon_robustesse></seee_taxon_robustesse>
<libelle_statut>Validé</libelle_statut>
<observation>test</observation>
<meteo_libelle>Faiblement nuageux</meteo_libelle>
<cs_moy>9.36</cs_moy>
<rive_libelle>gauche</rive_libelle>
<robustesse_value>10.06</robustesse_value>
<cs_min>4</cs_min>
<organisme>DREAL</organisme>
<ref_dossier>polo</ref_dossier>
<robustesse_niveau_trophique_id></robustesse_niveau_trophique_id>
<date_op>2013-09-05</date_op>
<classe_etat_id>1</classe_etat_id>
<nbtaxon_contrib>11</nbtaxon_contrib>
<nbtaxon_het>0</nbtaxon_het>
<wgs84_y></wgs84_y>
<wgs84_x></wgs84_x>
<coef_max>2</coef_max>
<robustesse_classe_etat_id>1</robustesse_classe_etat_id>
<niveau_trophique_id></niveau_trophique_id>
<station>LA CANCHE À AUBIN SAINT VAAST (62)</station>
<releve_dce>1</releve_dce>
<y>7034085.08</y>
<x>627094.934</x>
<id_op_controle>5</id_op_controle>
<typo_name>TG14/3-11</typo_name>
<hydrologie_libelle>Etiage normal</hydrologie_libelle>
<cours_eau>La Canche</cours_eau>
<taxon_robustesse>AMBRIP</taxon_robustesse>
<nbtaxon_pha>4</nbtaxon_pha>
<eqr_value>0.99</eqr_value>
<nbtaxon_pte>0</nbtaxon_pte>
<robustesse_eqr_value>1.07</robustesse_eqr_value>
<nbtaxon_bry>5</nbtaxon_bry>
<cs_max>13</cs_max>
<nbtaxon_lic>0</nbtaxon_lic>
<coef_moy>1.36</coef_moy>
<ibmr_value>9.28</ibmr_value>
<coef_min>1</coef_min>
<ek_nb_robustesse>2</ek_nb_robustesse>
<robustesse_classe_etat_libelle>Très bon</robustesse_classe_etat_libelle>
<nbtaxon_alg>2</nbtaxon_alg>
<classe_etat_libelle>Très bon</classe_etat_libelle>
<nbtaxon_total>11</nbtaxon_total>
<nbtaxon_steno3>0</nbtaxon_steno3>
<nbtaxon_steno2>4</nbtaxon_steno2>
<nbtaxon_steno1>7</nbtaxon_steno1>
<cs_moy>9.36</cs_moy>
<robustesse_value>10.06</robustesse_value>
<cs_min>4</cs_min>
<classe_etat_id>1</classe_etat_id>
<nbtaxon_contrib>11</nbtaxon_contrib>
<nbtaxon_het>0</nbtaxon_het>
<coef_max>2</coef_max>
<robustesse_classe_etat_id>1</robustesse_classe_etat_id>
<id_op_controle>5</id_op_controle>
<taxon_robustesse>AMBRIP</taxon_robustesse>
<nbtaxon_pha>4</nbtaxon_pha>
<eqr_value>0.99</eqr_value>
<unite_releve><terre_marne_tourbe></terre_marne_tourbe>
<radier>4</radier>
<pc_vegetalisation>25</pc_vegetalisation>
<type_ur_id>4</type_ur_id>
<blocs_dalles></blocs_dalles>
<pc_helophyte></pc_helophyte>
<pc_lichen></pc_lichen>
<type_ur_libelle>Unique</type_ur_libelle>
<eclaire>4</eclaire>
<largeur_UR>15</largeur_UR>
<facies_libelle>Radier</facies_libelle>
<tres_ombrage></tres_ombrage>
<pc_heterot></pc_heterot>
<debris_org></debris_org>
<pl_lentique>0</pl_lentique>
<fosse_dissipation>0</fosse_dissipation>
<artificiel></artificiel>
<pc_phanero></pc_phanero>
<pc_UR>100</pc_UR>
<rapide>0</rapide>
<sable_graviers>2</sable_graviers>
<racines></racines>
<facies_autre_type_id></facies_autre_type_id>
<facies_autre_type_libelle></facies_autre_type_libelle>
<cailloux_pierres>5</cailloux_pierres>
<periphyton_libelle></periphyton_libelle>
<cascade>0</cascade>
<ombrage></ombrage>
<vase_limons></vase_limons>
<pl_courant>4</pl_courant>
<numUR>1</numUR>
<autreTypeClass></autreTypeClass>
<id_UR>18</id_UR>
<facies_id>6</facies_id>
<id_op_controle>5</id_op_controle>
<pc_bryo></pc_bryo>
<longueur_UR>100</longueur_UR>
<pc_algues></pc_algues>
<pc_flottante></pc_flottante>
<peu_ombrage>4</peu_ombrage>
<ch_lentique>0</ch_lentique>
<pc_immerg></pc_immerg>
<mouille>0</mouille>
<tres_eclaire></tres_eclaire>
<ch_lotique>0</ch_lotique>
<p5></p5>
<p4></p4>
<p3>3</p3>
<p2>5</p2>
<p1></p1>
<v5>3</v5>
<v4>5</v4>
<v3></v3>
<v2></v2>
<v1></v1>
<periphyton_id></periphyton_id>
</unite_releve>
<taxon><cote_spe>5</cote_spe>
<cf>0</cf>
<nom_taxon>Amblystegium riparium</nom_taxon>
<cd_sandre>1219</cd_sandre>
<coef_steno>2</coef_steno>
<cd_valide>LEORIP</cd_valide>
<id_ligne_op_controle>24</id_ligne_op_controle>
<id_taxon>AMBRIP</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>2</pc_UR1>
<cd_taxon>AMBRIP</cd_taxon>
<cd_contrib>AMBRIP</cd_contrib>
</taxon>
<taxon><cote_spe>10</cote_spe>
<cf>0</cf>
<nom_taxon>Apium nodiflorum</nom_taxon>
<cd_sandre>1974</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>HELNOD</cd_valide>
<id_ligne_op_controle>29</id_ligne_op_controle>
<id_taxon>APINOD</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>0.9</pc_UR1>
<cd_taxon>APINOD</cd_taxon>
<cd_contrib>APINOD</cd_contrib>
</taxon>
<taxon><cote_spe>10</cote_spe>
<cf>0</cf>
<nom_taxon>Callitriche platycarpa</nom_taxon>
<cd_sandre>1702</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>CALPLA</cd_valide>
<id_ligne_op_controle>30</id_ligne_op_controle>
<id_taxon>CALPLA</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>0.5</pc_UR1>
<cd_taxon>CALPLA</cd_taxon>
<cd_contrib>CALPLA</cd_contrib>
</taxon>
<taxon><cote_spe>13</cote_spe>
<cf>0</cf>
<nom_taxon>Cinclidotus riparius</nom_taxon>
<cd_sandre>1321</cd_sandre>
<coef_steno>2</coef_steno>
<cd_valide>CINRIP</cd_valide>
<id_ligne_op_controle>25</id_ligne_op_controle>
<id_taxon>CINRIP</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>2</pc_UR1>
<cd_taxon>CINRIP</cd_taxon>
<cd_contrib>CINRIP</cd_contrib>
</taxon>
<taxon><cote_spe>6</cote_spe>
<cf>0</cf>
<nom_taxon>Cladophora sp.</nom_taxon>
<cd_sandre>1124</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>CLASPX</cd_valide>
<id_ligne_op_controle>22</id_ligne_op_controle>
<id_taxon>CLASPX</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>15</pc_UR1>
<cd_taxon>CLASPX</cd_taxon>
<cd_contrib>CLASPX</cd_contrib>
</taxon>
<taxon><cote_spe>12</cote_spe>
<cf>0</cf>
<nom_taxon>Fissidens crassipes</nom_taxon>
<cd_sandre>1294</cd_sandre>
<coef_steno>2</coef_steno>
<cd_valide>FISCRA</cd_valide>
<id_ligne_op_controle>26</id_ligne_op_controle>
<id_taxon>FISCRA</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>0.9</pc_UR1>
<cd_taxon>FISCRA</cd_taxon>
<cd_contrib>FISCRA</cd_contrib>
</taxon>
<taxon><cote_spe>10</cote_spe>
<cf>0</cf>
<nom_taxon>Fontinalis antipyretica</nom_taxon>
<cd_sandre>1310</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>FONANT</cd_valide>
<id_ligne_op_controle>27</id_ligne_op_controle>
<id_taxon>FONANT</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>9</pc_UR1>
<cd_taxon>FONANT</cd_taxon>
<cd_contrib>FONANT</cd_contrib>
</taxon>
<taxon><cote_spe>10</cote_spe>
<cf>0</cf>
<nom_taxon>Phalaris arundinacea</nom_taxon>
<cd_sandre>1577</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>PHAARU</cd_valide>
<id_ligne_op_controle>31</id_ligne_op_controle>
<id_taxon>PHAARU</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>0.5</pc_UR1>
<cd_taxon>PHAARU</cd_taxon>
<cd_contrib>PHAARU</cd_contrib>
</taxon>
<taxon><cote_spe>12</cote_spe>
<cf>0</cf>
<nom_taxon>Rhynchostegium riparioides</nom_taxon>
<cd_sandre>1268</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>PLTRIP</cd_valide>
<id_ligne_op_controle>28</id_ligne_op_controle>
<id_taxon>RHYRIP</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>2</pc_UR1>
<cd_taxon>RHYRIP</cd_taxon>
<cd_contrib>RHYRIP</cd_contrib>
</taxon>
<taxon><cote_spe>4</cote_spe>
<cf>0</cf>
<nom_taxon>Vaucheria sp.</nom_taxon>
<cd_sandre>1169</cd_sandre>
<coef_steno>1</coef_steno>
<cd_valide>VAUSPX</cd_valide>
<id_ligne_op_controle>23</id_ligne_op_controle>
<id_taxon>VAUSPX</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>2</pc_UR1>
<cd_taxon>VAUSPX</cd_taxon>
<cd_contrib>VAUSPX</cd_contrib>
</taxon>
<taxon><cote_spe>11</cote_spe>
<cf>0</cf>
<nom_taxon>Veronica anagallis-aquatica</nom_taxon>
<cd_sandre>1955</cd_sandre>
<coef_steno>2</coef_steno>
<cd_valide>VERANA</cd_valide>
<id_ligne_op_controle>32</id_ligne_op_controle>
<id_taxon>VERANA</id_taxon>
<pc_UR2></pc_UR2>
<pc_UR1>0.5</pc_UR1>
<cd_taxon>VERANA</cd_taxon>
<cd_contrib>VERANA</cd_contrib>
</taxon>
</operation>
</operations>`

**Comment by equinton** [comment]
Pouvez-vous faire des copies d'écran des 3 onglets ? Ce sera plus simple que de relire le fichier xml (je n'ai pas de procédure d'import)

**Comment by equinton** [comment]
J'ai l'impression que les coordonnées géographiques sont hors zone, notamment la valeur y : 
<coord_y>2600727</coord_y> 
Voici les valeurs autorisées (fichier param.ini) : 
lambert93Emin=70000
lambert93Emax=1200000
lambert93Nmin=6000000
lambert93Nmax=7200000

La zone Y doit être entourée d'une bordure jaune ou orange, pour signaler que la valeur entrée n'est pas celle attendue. Comme c'est une valeur obligatoire pour la validation, il est normal que le dossier ne soit pas validé.
