### ISSUE TITLE
accès Jtable en mode déconnecté du réseau

### ISSUE THREAD

**Issue by claplacetreyture** [Irstea/alisma#14]
En mode déconnecté du réseau l'accès aux tables (stations, cours d'eau, taxons) ne fonctionne pas. Apparait juste un petit carré gris à la place de la JTable.
Christophe.

**Comment by equinton** [comment]
Le problème n'est pas forcément lié au réseau, je l'ai également reproduit en étant connecté pour les écrans suivants :
- référentiel Irstea
- consultation des relevés

D'ailleurs, la réouverture de la fiche de consultation des relevés est incohérent (fenêtre vide hors limites)
