### ISSUE TITLE
Différence de calcul entre le SEEE et ALISMA

### ISSUE THREAD

**Issue by equinton** [Irstea/alisma#15]
Les calculs réalisés entre le logiciel Alisma et le SEEE présentent des différences significatives.
![image004](https://cloud.githubusercontent.com/assets/6715861/24098107/2bc15b44-0d69-11e7-83b6-9f0d4bc7e016.png)
![image003](https://cloud.githubusercontent.com/assets/6715861/24098109/2bc1cffc-0d69-11e7-94be-8e89f67a96a2.png)
![image002](https://cloud.githubusercontent.com/assets/6715861/24098108/2bc15554-0d69-11e7-923d-ab77fd44afe5.png)

Signalé par L. Gasnier

**Comment by florida63** [comment]
Il me semble que le code Taxon HILSPX devrait avoir un Csi (cote spécifique de niveau trophique) de 15 et Ei (un coef de sténoécie) de 2. 

Ça explique certainement en partie les différences de calcul. Sauf erreur de ma part votre calcul ne semble pas être calé sur le même référentiel que le SEEE.

Lilian

**Comment by equinton** [comment]
En fait, c'est bien le cas : HILSPX est un synonyme de HILRIV qui, lui, a bien les bonnes valeurs (15 et 2 respectivement).

Dans le cas du calcul du taxon à enlever pour la robustesse, je pense que le logiciel Alisma ne prend pas correctement en compte le taxon de référence. Je corrigerai ça pour la prochaine version.

Peut-être est-ce la cause de l'erreur de calcul de l'indicateur principal, mais j'en doute. Je vérifierai de toute façon.

Merci pour votre retour,

Éric Q.

**Comment by florida63** [comment]
En systématique HILSPX n'est pas un synonyme au sens strict de HILRIV mais je comprend l'idée de base.  

Pour revenir à l'erreur de calcul, il me semble que le script R utilisé dans la SEEE n'est pas exempt d'erreur dans certains cas. Je vous ferai un retour.

Lilian

**Comment by equinton** [comment]
Pb résolu : le logiciel ne prenait pas correctement en compte le taxon contrib. Les calculs sont maintenant corrects.
Disponible dans la prochaine version.
