### ISSUE TITLE
ordre de saisie des données mésologiques

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#21]
(LG AERMC) : dans données mésologiques, "type de faciès" et "type de substrat" ne sont pas dans le même ordre que dans la feuille excel. Est ce volontaire ? Est ce adapté à la feuille de terrain ?

**Comment by SandrineLORIOT** [comment]
(MS AEAG) : Même remarque que LG AERMC, sur l’ordre des types de faciès de substrats. Toujours dans une logique de sécurité lors des saisie par du personnel non technique, il serait peut-être intéressant de réajuster cela.

**Comment by equinton** [comment]
Pouvez-vous indiquer l'ordre dans lequel vous voulez les informations ? Je ne connais pas l'appli Excel...

**Comment by SandrineLORIOT** [comment]
(MS AEAG) : Il serait préférable de conserver l’ordre de la feuille de relevé Excel en pj afin d’éviter toute erreur de saisie.
Ex ordre type de faciès de la fiche stationnelle : 
1.	Chenal lentique,
2.	Plat lentique,
3.	Mouille,
4.	Fosse dissipation,
5.	Chenal lotique,
6.	Radier,
7.	Cascade,
8.	Plat courant,
9.	Rapide, 
10.	Autre type
