### ISSUE TITLE
importer un fichier XML

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#22]
(LG AERMC) : possibilité d'importer un fichier XML exporté d'une autre base pour permettre d'intégrer les opérations de nos prestataires dans la base Agence

**Comment by florida63** [comment]
Le format Quesu du Sandre serait un plus

http://www.sandre.eaufrance.fr/ftp/documents/fr/scn/quesu/3.1/sandre_scenario_quesu_3.1.pdf

**Comment by SandrineLORIOT** [comment]
(EO DREAL PDL) : En terme de fonctionnalités à implémenter, la première qui nous est apparue est, comme l'indique Laurent, une fonction d'import de fichiers. Nous avons mis en place un outil interne pour,  à partir des feuilles de terrain et de paillasse, aboutir automatiquement à la liste floristique et aux recouvrements par UR qui sont directement "copiables" dans le fichier excel pré existant à alisma.
L'idéal serait donc via un fichier xml et/ou csv de s'éviter la re saisie dans alisma.

**Comment by SandrineLORIOT** [comment]
(MS AEAG) : Même remarque que LG AERMC, l’intérêt d’importer et d’exporter un xml dans notre base interne

**Comment by florida63** [comment]
Quesu est parfait pour ça. Il respecte la codification sandre et facilite l'intéropérabilité entre application.

**Comment by equinton** [comment]
Format XML interne. 
Développements complémentaires possibles par volontaires ?
