### ISSUE TITLE
ajouter un export intermédiaire XML en cours de saisie

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#23]
(LG AERMC) : ajouter la possibilité d'exporter les opérations en XML après la saisie des données générales et mésologiques (dont le statut est encore "en saisie"). En effet, le contrôle des prestataires s'effectue en deux temps : après la phase terrain sur fourniture du fichier de description de la station, puis au rendu du rapport d'essai.

**Comment by equinton** [comment]
Souhaitez-vous un export global (généré depuis la fenêtre de la liste des relevés), ou uniquement dossier par dossier ? 
Dans quel format ? QUESU ou interne Alisma ?

**Comment by equinton** [comment]
Format d'export : XML
Export global

**Comment by equinton** [comment]
Plus de restriction sur le statut lors de l'export xml
