### ISSUE TITLE
saisie de la largeur avec décimale

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#27]
(MS AEAG) : Saisie de la largeur : décimale impossible à renseigner dans l’onglet « données générales », uniquement à l’unité. Dans l’onglet « données méso », décimale possible mais la case reste en rouge.

**Comment by equinton** [comment]
Préciser si la décimale a été saisie avec un point ou une virgule
Copie d'écran le cas échéant

**Comment by SandrineLORIOT** [comment]
(MS AEAG)  : lorsque la décimale est saisie en mode . (point), la décimale est acceptée. La question est donc résolue

**Comment by equinton** [comment]
Ajouter une transformation de la virgule en point pour les champs décimaux
Classe concernée : utils/NumericVerifier
