### ISSUE TITLE
type de faciès "autre"

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#28]
(MS AEAG) : Le type de faciès " autre" recouvrement ne peut-être laissé vide, il faut obligatoirement le renseigner. A ce titre il faudrait rajouter un champ « vide » qui l’accepte, car celui actuel n’est pas pris en compte.

**Comment by equinton** [comment]
Dans onglet 2, facies constitutifs des UR, dans la liste déroulante "autre type", rajouter une catégorie "autre"
