### ISSUE TITLE
cF et calcul de la robustesse

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#30]
(MS AEAG) : Sur un test de données, j’ai un taxon dominant mais « cf » qui est pris en compte dans le calcul de la robustesse, or sur la Fiches Irstea il est bien écarté et c’est le 2ème taxon dominant qui le remplace. Est-ce normal ?

**Comment by equinton** [comment]
Il faudrait avoir une copie de l'écran des taxons et préciser exactement ce qu'il se passe

**Comment by SandrineLORIOT** [comment]
(MS AEAG) : 
![robustesse](https://cloud.githubusercontent.com/assets/26956202/25230912/1c35b276-25d6-11e7-84c4-a2845acff55b.jpg)
![fiche irstea](https://cloud.githubusercontent.com/assets/26956202/25231031/85a605e4-25d6-11e7-8c0a-f31eac6e460f.png)

Sur mon relevé j’ai le taxon CALOBT qui est « cf ». En calculant les indices avec Alisma ma robustesse est de 12.05 et le taxon pris en compte est CALOBT. Or, sur mon relevé Irstea, ma robustesse est de 10.14 car le taxon pris en compte est BATSPX car étant cf CALOBT doit normalement être écarté (cf ficher relevé en pj).

**Comment by equinton** [comment]
Il faudrait préciser l'algorithme exact à prendre en compte : je n'ai pas compris à quoi servait cf...

**Comment by SandrineLORIOT** [comment]
Un élément de réponse : cF = Confer (= pour le Sandre "degré de confiance sur la détermination d'un taxon) est une case qui est cochée quand l'opérateur a un doute sur l'identité du taxon. Cette donnée n'est pas bancarisée dans Pandore Irstea et n'impacte par le calcul de l'IBMR car elle n'est pas prise en compte. Cocher cF est une indication pour mémoire pour l'opérateur. Il n'y a donc pas de raison pour que le cF coché ou non impacte le calcul de l'IBMR "robuste"
