### ISSUE TITLE
compatibilité Alisma et Mac

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#31]
(MS AEAG) : Alisma ne serait apparemment pas compatible avec les Mac (retour de l’informaticien de Monique Aubert)

**Comment by equinton** [comment]
Il faudrait avoir des informations techniques sur ce qui ne fonctionne pas ou les problèmes rencontrés

**Comment by SandrineLORIOT** [comment]
(MS AEAG) : je vous propose de vous laisser voir cela directement avec Monique Aubert, je n’ai aucune information sur le problème rencontré.

**Comment by AEAGMargauxSaut** [comment]
j'ai fait passer le message à Monique pour qu'elle vous contacte.
