### ISSUE TITLE
Saisie code Station

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#32]
Détail - remarque : quand on recherche une station par son code Sandre, la recherche n'est pas basée sur les premiers chiffres (ex 05....) mais sur n'importe quelle position où se trouve les chiffres saisis (ex 0105...)

Détail - remarque : Quand on a trouvé dans le menu déroulant la station souhaitée, on ne peut pas cliquer dessus pour valider le choix. La case Station reste incomplète avec les quelques chiffres saisis (capture d'écran) 

Ajout fonction à envisager : que le type national soit renseigné automatiquement quand on choisi un station car le référentiel Sandre des stations comporte cette information.
![code station](https://cloud.githubusercontent.com/assets/26956202/25736290/431879f4-3171-11e7-98d3-ca907bcdb4f0.png)

**Comment by equinton** [comment]
Premier point:
modifier la fonction Stations.searchByName pour ne plus faire la recherche partout dans la zone cd_station, mais uniquement sur la fin de la chaîne
Second point : non confirmé, la sélection est bien possible
Troisième point : ok, mais il faudrait disposer des données adéquates. Merci d'indiquer où on peut récupérer cette info.

**Comment by equinton** [comment]
La première zone est une zone de recherche, elle est normalement vide lors de la réouverture de la fiche.
Il est normal qu'elle reste incomplète.

**Comment by equinton** [comment]
1er point traité
2n point abandonné

**Comment by equinton** [comment]
zone semblant comprendre le code typologique de la station : TypeCEStationMesureEauxSurface

**Comment by equinton** [comment]
Récupération du fichier des stations au format json (moins volumineux que le XML) : 
wget http://services.sandre.eaufrance.fr/References/1.3.0/References.php?version=1.3.0&service=References&request=getReferenceElements&CdReferentiel=STQ&Filter=<Filter><Statut>0</Statut></Filter>&outputFormat=application/json&outputSchema=http://xml.sandre.eaufrance.fr/scenario/referentiel/3.1/sandre_sc_referentiel.xsd

**Comment by SandrineLORIOT** [comment]
C'est bien le champ "TypeCEStationMesureEauxSurface" qui resnseigne le "Type de la masse d'eau cours d'eau" http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:NSA:FRA:code:408:::referentiel:3.1:html
En consultant le référentiel Station de mesure des eaux superficielles du Sandre, je constate que ce champ est très peu renseigné. De plus, je crois me souvenir qu'il avait été dit depuis que la typologie pouvait être corrigée pour certaines stations en limite d'HER par exemple (voir avec Christian) et que donc une saisie manuelle serait préférable.
