### ISSUE TITLE
Menu déroulant données générales - turbidité

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#33]
Pour la turbidité : anomalie car "nulle ou faible" ne correspond pas au référentiel Sandre qui distingue  "nulle" ou "faible"
http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:PAR:FRA:code:6498:::referentiel:2:html

**Comment by equinton** [comment]
Définir une règle permettant de traiter les données déjà saisies : comment positionne-t-on les données déjà en "nulle ou faible" ? En nulle, ou en faible ?

**Comment by equinton** [comment]
Basculer en nulle et faible.
Les anciennes valeurs sont assignées à faible

**Comment by equinton** [comment]
prise en compte dans le script de modif
