### ISSUE TITLE
Export pdf - correction et évolution esthétique

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#37]
Evolution - esthétique
Faire passer à la ligne suivante la date du relevé et référence du dossier. Pour le moment la sortie donne bout à bout le nom de la station, la date, la référence du dossier

Correction
Les échelles sont approximatives 
Échelle : 0 : absent, 1 : < 1%, 2 : < 10%, 3 : < 25%, 4 : < 75%, 5 : >=75%
C’est en fait (avec des inférieur ou égal et des bornes inférieures et supérieures). 
0 : x = absent ;  1 : x<1% ; 2 : 1 ≤x≤10% ; 3 : 10≤x≤25% ; 4 : 25 ≤x ≤ 75% ; 5 : x ≥ 75%

Evolution - esthétique
Le tableau des taxons comporte des traits d'épaisseur variable (copie d'écran)
![pdf_taxons](https://cloud.githubusercontent.com/assets/26956202/25736885/f143ff3c-3174-11e7-8ecb-263bb84df384.png)

**Comment by equinton** [comment]
Les échelles ne sont pas approximatives, elles se lisent de gauche à droite.
Pour des questions de caractères (le signe <= est complexe à coder si on le veut sur une seule position) et de longueur de zone, le parti-pris a été d'afficher les échelles de manière incrémentale. Par exemple, une valeur de 26 % doit se lire ainsi : 
- ce n'est pas absent
- ce n'est pas < 1
- ce n'est pas < 10
- ce n'est pas < 25
- c'est inférieur à 75, donc le code est 4
La lecture du code se fait donc dans le sens décroissant : 
- 4 est < 75 % et >= à 25 %

**Comment by equinton** [comment]
L'esthétique des traits n'est pas modifiable, c'est lié à l'outil utilisé pour générer les tableaux (calcul automatique).
