### ISSUE TITLE
Table de référence "cours d'eau" 

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#38]
Il y a une table de référence "cours d'eau" mais il n'y a pas de champs de saisie "cours d'eau" dans Alisma. 
Est ce normal ?

**Comment by equinton** [comment]
oui, les stations sont rattachées aux cours d'eau : la sélection d'une station entraîne forcément, en base de données, le rattachement au cours d'eau.
La table ne sert que pour les interrogations directes dans la base de données.
