### ISSUE TITLE
Coordonnées GPS - Lambert 93 et wgs84

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#39]
Question:
Il est obligatoire de saisir les données en Lambert 93. Or, si elles le sont, mais qu'elles n'ont pas été également saisies en wgs84, l'onglet "données générales" n'est pas validé (point d'exclamation et non coche verte). Est ce normal ? La double saisie des coordonnées GPS dans les 2 systèmes est elle requise ?

**Comment by equinton** [comment]
Les données ne sont pas obligatoires, mais recommandées. Même fonctionnement que pour les données mésologiques.
À confirmer la désactivation de cette recommandation.
