### ISSUE TITLE
rive (coordonnées GPS)

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#40]
Concordance référentiel Sandre ? évolution ? 
Le référentiel Sandre comporte un "Endroit de la rivière" 
http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:NSA:FRA:code:811:::referentiel:3.1:html
Qui permet de préciser amont droit, aval gauche, etc
Il me semble que c'était une demande de l'AE Rhin Meuse

**Comment by equinton** [comment]
Ajouter la précision Amont dans la coordonnée X (libellé en saisie)

**Comment by equinton** [comment]
Modifications apportées en base de données (script de modification)
