### ISSUE TITLE
visuel calcul des indicateurs 

### ISSUE THREAD

**Issue by SandrineLORIOT** [Irstea/alisma#41]
![calcul indicateur](https://cloud.githubusercontent.com/assets/26956202/25738048/40366372-317b-11e7-9164-862676ac4c05.png)

- EQR : quand le type national n'est pas renseigné, l'EQR donné est la valeur de l'IBMR. Il serait préférable de lire "NULL" ou rien du tout. A voir si le type national est renseigné automatiquement via un lien avec la table station, la question ne se posera plus.

- Lisibilité des résultats : à améliorer ? Pour le moment, je ne sais pas si il faut lire en ligne ou en colonne entre IBMR, EQR, Classe d'état et la même chose en tenant compte de la robustesse. 
Peut être envisager de mettre sur une même ligne IBMR, EQR, Classe d'Etat
en dessous la robustesse en renommant "Robustesse" par "Note IBMR Robuste" ou raccourci "IBMR Robuste' pour concordance avec le Sandre
http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:PAR:FRA:code:8063:::referentiel:2:html

-IBMR officiel ? qu'est ce que cela signifie ?

- date, version de calcul : ne sont pas renseignés

**Comment by equinton** [comment]
L'IBMR officiel est celui calculé par le SEEE. Les dates et versions de calcul sont les informations concernant ce calcul officiel.
Dans l'exemple ci-dessus, le calcul SEEE n'a pas été réalisé.
