### ISSUE TITLE
données décimales pour la végétalisation

### ISSUE THREAD

**Issue by mosaiqueenvironnement** [Irstea/alisma#53]
Bonjour,
dans la page "végétalisation" d'Alisma, pour remplir les cases de pourcentage de recouvrement, il n'est pas possible de rentrer des nombres décimaux. Or, pour certains paramètres où le pourcentage est très faible : 0,1 par exemple pour le pourcentage de végétation flottante, comment procède-t-on? Doit-on arrondir au nombre le plus proche ce qui ferait 0 ici (ce qui est faux), ou au chiffre supérieur : 1%, ce qui est très loin de la réalité également.
Merci d'avance pour votre réponse
Cordialement
Eric BOUCARD (Mosaique environnement : 04 78 03 18 18/ agence@mosaique-environnement.com)

**Comment by equinton** [comment]
Transformer tous les pourcentages en nombres décimaux (% veg. flottante et consorts)

**Comment by mosaiqueenvironnement** [comment]
Je ne comprends pas trop la réponse. Sur le logiciel, on peut pas 
rentrer de nombre décimal d'où ma question.
Les pourcentages doivent-ils donc être arrondis à l’unité inférieure ou 
supérieure? où doit-on les rentrer en nombre décimal, et si oui, comment 
peut-on faire, puis que le logiciel n'accepte pas de nombre décimal?

merci d'avance

Eric BOUCARD
Associé
Ingénieur écologue - Botaniste phytosociologue

www.mosaique-environnement.com <http://www.mosaique-environnement.com/>
Agence Mosaïque Environnement
111 rue du 1er Mars 1943
69100 VILLEURBANNE
Tel: 04 78 03 18 18 ou 09 51 09 98 18
Fax: 04 78 03 71 51
Port: 07 61 54 52 80



N° de déclaration d’activité en tant que prestataire de formation :
82 69 14158 69 auprès du préfet de région de Rhône-Alpes-Auvergne

**Comment by equinton** [comment]
C'est corrigé dans la version 1.2.1, qui devrait être mise à disposition pour tests prochainement par Ch. Chauvin.

**Comment by mosaiqueenvironnement** [comment]
très bien, merci pour l'information.
cordialement

Eric BOUCARD
Associé
Ingénieur écologue - Botaniste phytosociologue

www.mosaique-environnement.com <http://www.mosaique-environnement.com/>
Agence Mosaïque Environnement
111 rue du 1er Mars 1943
69100 VILLEURBANNE
Tel: 04 78 03 18 18 ou 09 51 09 98 18
Fax: 04 78 03 71 51
Port: 07 61 54 52 80



N° de déclaration d’activité en tant que prestataire de formation :
82 69 14158 69 auprès du préfet de région de Rhône-Alpes-Auvergne
