### ISSUE TITLE
Export de données au format csv - questions

### ISSUE THREAD

**Issue by lucieClavel** [Irstea/alisma#54]
Bonjour
Voir manuel d'installation et d'utilisation p 13 et 14 
1- Pourquoi l'export csv n'est pas accessible depuis l'interface Alisma?
2-Pourquoi l'export csv n'est pas basé directement sur une requête sql lancée par Alisma comme il en est fait mention dans la remarque du manuel d'utilisation /

**Comment by equinton** [comment]
Bonjour,

L'export CSV a une structure formalisée, qui ne correspond pas à la structure de la base de données qui est utilisée dans l'application. Générer les fichiers depuis l'application aurait été très complexe, alors que celle-ci génère déjà des fichiers au format xml, utilisés pour les échanges ou pour la génération des fiches PDF.

Il était plus simple de générer un script Java avec l'outil Talend OpenStudio for Data Integration, qui prend en entrée les fichiers xml et génère les CSV correspondants. De plus, la modification du script est plus simple que d'intervenir dans le code d'Alisma.

La référence à SQL dans le manuel d'utilisation est plus pour indiquer qu'il est plus simple de chercher les données directement dans la base de données que d'utiliser les fichiers CSV générés.

Cordialement,

Eric Quinton

**Comment by lucieClavel** [comment]
Bonjour
Je ne suis pas d'accord, la plupart des utilisateurs d'alisma ne savent pas faire une requête sql, les techniciens des labo des DREAL seront très contents de pouvoir éditer le csv (qui devrait être un .txt en principe) sous xls ou ods et faire des tableaux croisés dynamiques ou des graphes.
Je pense qu'il y a une erreur de casting il n'y a pas que des Laurent Gasnier qui vont utiliser Alisma, d'ailleurs Laurent Gasnier ne l'utilisera pas au quotidien.

**Comment by equinton** [comment]
La génération des fichiers CSV est possible grâce aux utilitaires d'Alisma, et ils correspondent au format imposé : les utilisateurs peuvent les manipuler comme ils le souhaitent.
La procédure de génération ne pouvait pas être intégrée facilement dans l'application, d'où le passage par un script dédié.
Le script travaille à partir des fichiers générés en xml, sans interroger directement la base de données, pour de nombreuses raisons techniques.

L'interrogation via SQL permet d'aller beaucoup plus loin dans la recherche d'informations, et les données présentes dans les CSV ne sont qu'une extraction (partielle) des données gérées (mais conforme à ce qui a été demandé).
