### ISSUE TITLE
Export de données au format csv utilisation

### ISSUE THREAD

**Issue by lucieClavel** [Irstea/alisma#55]
Bonjour
Je cherche à exporter mes données au format csv (j'ai une version embarquée de l'application).
Au préalable j'ai déjà exporté des données au format xml qui sont stockées dans C:\alisma\export
Je vais dans C:\alisma\utilitaires, j'exécute export_csv.bat 
![image](https://user-images.githubusercontent.com/44400725/47358596-6e799600-d6ca-11e8-979a-d3ea799133cf.png)
j'appuie sur une touche pour continuer
Après je ne retrouve pas les fichiers _taxon.csv et _facies.csv. Où sont-ils sensés être enregistrés ?
Merci par avance

**Comment by equinton** [comment]
C'est dans le dossier alisma/export qu'on retrouve tous les fichiers générés.

**Comment by equinton** [comment]
Une erreur a été générée lors du lancement du script, en raison d'un problème de mémoire insuffisante dans le PC.

Pour corriger le script, il faut éditer le fichier : 
alisma/utilitaires/export_csv_calcul/export_csv_calcul_run.bat
et modifier la ligne 3, en changeant l'option -Xmx2048M en -Xmx1024M, voire en -Xmx512M

Merci d'indiquer si la modification permet l'exécution ou non du script, avec génération des fichiers csv.

**Comment by lucieClavel** [comment]
Bonjour
Merci pour ta réponse
En remplaçant par -Xmx512M j'arrive à lancer le script, en revanche, il ne renvoie des fichiers qui ne comportent que l'entête et pas de données.
