### ISSUE TITLE
[Export PDF]

### ISSUE THREAD

**Issue by thilinipdw** [Irstea/alisma#6]
Bonjour, 
Je rencotre des difficultés lorsque il s'agit d'exporter mes données saisies en version PDF. Les données sont bien enregistrée (j'arrive à les consulter à postériori) mais lorsque j'appuie sur "Export PDF", le bouton ne fonctionne pas. 
Merci.

**Comment by equinton** [comment]
Bonjour,

Dans le fichier param.ini, dans la section [others], vous avez une entrée pathFolderExport : vérifiez que le dossier existe bien, et que vous avez les droits d'écriture. Les fichiers sont générés dans ce dossier.

Pour vérifier les messages d'erreur, vous avez peut-être un fichier alisma.log à la racine du dossier d'installation : regardez s'il y a des informations qui aideraient à réaliser le diagnostic. Vous pouvez également lancer le logiciel dans une fenêtre DOS (Démarrer > Exécuter > cmd.exe) pour visualiser les messages générés par Java.

Cordialement,

**Comment by thilinipdw** [comment]
Bonjour,
Très bien. Merci.

Bien cordialement, 
Thilini PASQUWELAGE

**Comment by equinton** [comment]
Ajout de tests et de messages d'information dans la version 1.1, pour limiter ce type de problèmes.
